<footer id="Contentplaceholder1_TBE379D1F026_Col00" class="sf_colsIn footer-hover-links-light" data-sf-element="Container" data-placeholder-label="footer">
    <div id="Contentplaceholder1_TBE379D1F027_Col00" class="sf_colsIn he_footer" data-sf-element="Container" data-placeholder-label="Container">
    <div id="Contentplaceholder1_TBE379D1F028_Col00" class="sf_colsIn container" data-sf-element="Container" data-placeholder-label="Container">
        <div class="row" data-sf-element="Row">
        <div id="Contentplaceholder1_TBE379D1F029_Col00" class="sf_colsIn col-xl-2 col-lg-3 split screen-lg logos" data-sf-element="Column 1" data-placeholder-label="Column 1">
        <div>
        <div class="logo"><h2 class="d-none">GOV.CO</h2><a href="https://www.gov.co" target="_blank" title="Logo de govco, lleva a la página web" data-sf-ec-immutable="" onfocus="toggleFocus(this)" onblur="toggleFocus(this)"><img src="images/govco-logo.svg?sfvrsn=bba74786_1" alt="Ir al portal gov.co"></a>
        </div><div class="logo_co"><a href="https://www.colombia.co" target="_blank" title="Logo de Marca País Colombia, lleva a la página web" onfocus="toggleFocus(this)" onblur="toggleFocus(this)"><img src="images/marca_pais_colombia_logo.svg?sfvrsn=582b81ee_1" alt="Ir al portal colombia.co"></a></div>    
</div>
    </div>
     <div id="Contentplaceholder1_TBE379D1F029_Col01" class="sf_colsIn col-xl-6 col-lg-5 split" data-sf-element="Column 2" data-placeholder-label="Column 2">
<div>
    <h2>Plataforma de Competitividad Regional - Competitivas</h2><p class="text-color-light">Dirección: Calle 28 No 13 A – 15, Bogotá, Colombia<br>Código Postal: 111711<br>Horario de Atención: Lunes a Viernes 7:00 a.m. - 6:00 p.m.
            </p><ul class="he_footer_redes"><li><a href="https://twitter.com/MincomercioCo" target="_new" title="Visitar la red social: twitter" data-sf-ec-immutable="" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">
 <em class="fab fa-twitter fa-circulo"></em><div class="fa_text">@MincomercioCo</div></a>
 </li><li><a href="https://www.youtube.com/mincomerciocolombia" target="_new" title="Visitar la red social: youtube" data-sf-ec-immutable="" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">
 <em class="fab fa-youtube fa-circulo"></em><div class="fa_text">@Mincomerciocolombia</div></a>
 </li><li><a href="https://www.facebook.com/pages/Ministerio-de-Comercio-Industria-y-Turismo/144621955578773" target="_new" title="Visitar la red social: facebook" data-sf-ec-immutable="" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">
 <em class="fab fa-facebook fa-circulo"></em><div class="fa_text">@MincomercioCo</div></a>
 </li><li><a href="https://www.instagram.com/mincomercioco/" target="_new" title="Visitar la red social: instagram" data-sf-ec-immutable="" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">
 <em class="fab fa-instagram fa-circulo"></em><div class="fa_text">@Mincomercioco</div></a>
 </li></ul>    
</div>
    </div>
     <div id="Contentplaceholder1_TBE379D1F029_Col02" class="sf_colsIn col-lg-4 no-split" data-sf-element="Column 3" data-placeholder-label="Column 3">
<div>
    <h3 class="text-3 font-weight-bold"><span class="fa fa-phone"></span>Contacto</h3><p class="text-color-light">Teléfono Conmutador: +57 601 606-7676 <br>Línea Gratuita: 01 800 0944 570 <br>Linea Anticorrupción: 01 800 0958 283 <br>Correo Competitivas: <a href="mailto:competitivas@mincit.gov.co" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">competitivas@mincit.gov.co</a><br>Correo Institucional: <a href="mailto:info@mincit.gov.co" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">info@mincit.gov.co</a> <br>Correo de notificaciones judiciales: <br><a href="mailto:notificacionesjudiciales@mincit.gov.co" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">notificacionesjudiciales@mincit.gov.co</a> <br></p><div class="MFooter"><a href="https://competitivas.gov.co/normatividad" target="_blank" data-sf-ec-immutable="">Normatividad</a>
 <a href="https://competitivas.gov.co/mapa-sitio" target="_blank" data-sf-ec-immutable="">Mapa del sitio</a>
 <a href="https://www.mincit.gov.co/servicio-ciudadano/politicas-de-tratamiento-de-datos-personales" target="_blank" data-sf-ec-immutable="" onfocus="toggleFocus(this)" onblur="toggleFocus(this)">Políticas</a>
</div>    
</div>
    </div>
     <div id="Contentplaceholder1_TBE379D1F029_Col03" class="sf_colsIn col-lg-2 no-split split-top screen-md-sm logos_movil" data-sf-element="Column 4" data-placeholder-label="Column 4">
    </div>
</div>

</div>

</div>
</footer>