<div class="navbar navbar-expand-lg navbar-govco navbar-expanded">
    <div class="navbar-container container">
        <div class="navbar-logo float-left">
            <a href="https://www.gov.co" target="_blank" title="Logo de govco, lleva a la página web">
                <img src="images/govco-logo.svg" width="120" alt="govco-logo" title="Ir al portal gov.co">
            </a>
        </div>
        <div class="nav-item-primary ml-auto mr-2"></div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 my-4 col-md-12 d-flex justify-content-between align-items-center">
            <a href="https://competitivas.gov.co" target="_blank">
                <img src="images/logo.png" title="Ir al inicio del portal" height="50px">
            </a>
            <a href="https://www.mincit.gov.co" target="_blank">
            <img src="images/logo-mincit.png" title="Logo del Mininterio de Comercio, lleva a la página web" height="50px">
            </a>
            
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row bg-search">
        <div class="col-md-10">

        </div>
        <div class="col-md-2">
            <form action="https://competitivas.gov.co/resultados" method="GET" target="_blank" class="form-search">
                <input type="hidden" name="indexCatalogue" value="sitio-web">
                <div class="input-group rounded">
                <input type="search" name="searchQuery" class="form-control rounded form-search" placeholder="Buscar..." aria-label="Search" aria-describedby="search-addon" />
                <button class="input-group-text border-0" id="search-addon">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                        </svg>
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>