<div class="navbar navbar-expand-lg navbar-govco navbar-expanded">
    <div class="navbar-container container">
        <div class="navbar-logo float-left">
            <a href="https://www.gov.co" target="_blank" title="Logo de govco, lleva a la página web">
                <img src="images/govco-logo.svg" width="120" alt="govco-logo" title="Ir al portal gov.co">
            </a>
        </div>
        <div class="nav-item-primary ml-auto mr-2"></div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 my-4 col-md-12 d-flex justify-content-between align-items-center">
            <a href="https://competitivas.gov.co" target="_blank">
                <img src="images/logo.png" title="Ir al inicio del portal" height="50px">
            </a>
            <a href="https://www.mincit.gov.co" target="_blank">
            <img src="images/logomincit2022.png" title="Logo del Mininterio de Comercio, lleva a la página web" height="50px">
            </a>
            
        </div>
    </div>
</div>